version: 2
jobs:
   build:
     machine:
       image: circleci/classic:201709-01
     environment:
       NATS_URI:  nats://127.0.0.1:4222
       ROOTPATH: /home/circleci/.go_workspace/src/github.com/ernestio
       NATS_URI_TEST:  nats://127.0.0.1:4222
       GOBIN: /home/circleci/.go_workspace/bin
       CURRENT_INSTANCE: https://ernest.local
       JWT_SECRET: test
       IMPORT_PATH: "github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
       ERNEST_LOG_FILE: '/tmp/ernest.log'
       ERNEST_APPLY_DELAY: 1
       ERNEST_CRYPTO_KEY: mMYlPIvI11z20H1BnBmB223355667788
     working_directory: /home/circleci/.go_workspace/src/github.com/ernestio/usage-store
     steps:
       - checkout
       - run: 
           name: Setup Hosts File
           command: echo 127.0.0.1 ernest.local | sudo tee -a /etc/hosts
       - run: 
           name: Install Dependencies
           command: |
             make dev-deps
             docker run --name postgres -d -p 5432:5432 postgres:9.6.5-alpine
             sudo apt update && sudo apt install postgresql-client
             echo "CREATE DATABASE usage;" | psql -U postgres -h 127.0.0.1
       - run: 
           name: Code Analysis
           command: make lint
       - run: 
           name: Unit Tests
           command: make test
       - run: 
           name: Integration Tests
           command: |
             docker stop postgres
             git clone git@github.com:ernestio/toolset.git /tmp/toolset/
             cd /tmp/toolset/ernestci/ && bundle install
             ruby /tmp/toolset/ernestci/run.rb $CIRCLE_WORKING_DIRECTORY/.ernest-ci
